<?php
$markers = array();
$countrys = $this->getCountries();
$agruments = [];
if($curPage = $block-> getcurPageCode()) {
    $agruments['p'] = $curPage;
}
$country =$block->getCountryCode();
$dealertype = $block->getDealertypeCode();
$city = $block->getCityCode();
$zipcode = $block->getZipCode();
$knpart = $block->getProductnumCode();   
$pincodefound = $this->getPincodefoundCode();    
	$picodecheck=$block->checkCountry($country);
	if($picodecheck==0)
	{
	$flag=0;
	$display='style="display:none";';
	}else{
	$flag=1;
	$display='';	
	}
?>
<?php echo $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
<div class="store-list-container">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="search-form">
                <form action="<?php echo $block->getUrl('locator/index/search', $agruments) ?>" method="GET" id="search_by_area" >
                    <h2><?php echo __('Search by Area') ?></h2>
 <input type="hidden" name="pincodefound" id="pincodefound" value="<?php $x = $flag ? '1' : '0';  echo $x;?>"/>
                    <div class="form-group">
                        <?php if (count($countrys)): ?>
                            <div class="col-md-6">
                                <div class="row">
                                    <label class="col-sm-4 control-label" for="country"><?php echo __('Country') ?>:</label>

                                    <div class="col-sm-8">
                                        <select name="country" id="country" class="input-text"
                                                title="<?php echo __('Country') ?>">
                                            <?php foreach ($countrys as $_country): ?>
             <option value="<?php echo $_country['value'] ?>" <?php echo $_country['value'] == $country ? 'selected' : ''; ?>><?php echo $_country['label'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="col-md-6">
                            <div class="row">
                                <label class="col-sm-4 control-label" for="state"><?php echo __('Dealer Type') ?>:</label>

                                <div class="col-sm-8">
								  <select name="dealertype" id="dealertype" class="input-text"  title="<?php echo __('Dealer Type') ?>">
								  	<option selected="selected" value="0" <?php echo $dealertype == 0 ? 'selected' : ''; ?>>All</option>
							<option value="1" <?php echo $dealertype == 1 ? 'selected' : ''; ?>>Automotive</option>
							<option value="2" <?php echo $dealertype == 2 ? 'selected' : ''; ?>>Powersports</option>
												  </select>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-6" id="cityocde" <?php echo $display;?> >
                            <div class="row">
                                <label class="col-sm-4 control-label" for="city"><?php echo __('City') ?>:</label>

                                <div class="col-sm-8">
                                    <input type="text" name="city" id="city" value="<?php echo $city ?>" title="<?php echo __('City') ?>"
                                           class="input-text"/>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6" id="zipcodes" <?php echo $display;?>>
                            <div class="row">
                                <label class="col-sm-4 control-label" for="zipcode"><?php echo __('Zip or Postal Code') ?></label>

                                <div class="col-sm-8">
                                    <input type="text" name="zipcode" id="zipcode" value="<?php echo $zipcode ?>"
                                           title="<?php echo __('Zipcode') ?>" class="input-text"/>
                                </div>
                            </div>
                        </div>
                         <div class="col-md-6">
                            <div class="row">
                                <label class="col-sm-4 control-label" for="knpart"><?php echo __('K&N Part # (Optional)') ?>:</label>

                                <div class="col-sm-8">
                                    <input type="text" name="productnum" id="productnum" value="<?php echo $knpart ?>"
                                           title="<?php echo __('K&N Part') ?>" class="input-text"/>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-sm-12">
                            <button class="action primary" title="<?php echo __('Search') ?>" type="submit">
                                <span><?php echo __('Search') ?></span></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

       
    </div>
</div>
<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
            var customurl = "<?php echo $block->getUrl('locator/index/checkpincode') ?>";
			$("#country").change(function(){
				var countryid = $(this).val();
			   var body = $('body').loader();

				body.loader('show');
                $.ajax({
                url: customurl,
                type: 'POST',
                dataType: 'json',
                data: {
                  countryid:countryid
                },
                complete: function(response) {             
                countryres = response.responseJSON.status;
                if(countryres=="0")
				{				
				$('#pincodefound').val(0);	
                $('#zipcodes').hide();				
				$('#cityocde').hide();
			    body.loader('hide');
				}else{
			   $('#pincodefound').val(1);	
				$('#zipcodes').show();	
				$('#cityocde').show();	
				body.loader('hide');
				}
                				
                },
                error: function (xhr, status, errorThrown) {
                    console.log('Error happens. Try again.');
					body.loader('hide');
                }
            });
			


			});
        });
    });
</script>

<?php 
if(($knpart!='')&&(($zipcode!='')||($city!=''))){
  $_StoreCollection = $this->getStoreCollection();
 ?>
<?php  $totalStoreCount = count($_StoreCollection);?>
<div class="store-list-container">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="store-list">
                <h3><?php echo __('Dealer List') ?></h3>

                <div class="items">
                    <?php if (!$totalStoreCount): ?>
                        <div class="alert alert-warning"><?php echo __('There are no stores.') ?></div>
                    <?php else: ?>
					<table class="grid_template_1" id="cph_dyn_gridview_1">
		<tbody><tr class="header_row">
			<th scope="col"><?php echo __('Name') ?></th><th scope="col"><?php echo __('Address') ?></th><th scope="col"><?php echo __('Contact Info') ?>.</th><th scope="col"><?php echo __('Distance (miles/km)') ?></th>
		</tr>                            <?php $i = 0;				
							$result = $this->getCoordinate();
							
							 foreach($countrys as $countries)
							 {
							 if($country==$countries['value'])	$country=$countries['label'];
								 
							 }		
                            foreach ($_StoreCollection as $store): $i++; 
							if($pincodefound>0){
					     	$dis=$this->getDistance($store->getLatitude(),$store->getLongitude(),$result[0]['latitude'],$result[0]['longitude']); 
							}else
								
								{
							$dis=array('miles'=>0,'kilometers'=>0);		
									
								}
						?>
                            
                              <tr class="stores">
                           
                                <td>
                        <?php echo $store->getName();if($store->getUrl()!=''){ ?>
			<a  href="<?php echo $store->getUrl(); ?>" target="_blank"><img src="<?php echo $this->getViewFileUrl('Born_DealerSearchApi::images/online.png'); ?>" alt="Buy Online"></a>
						<?php }	if($store->getInstaller()=='-1'){
						
						?>  <img src="<?php echo $this->getViewFileUrl('Born_DealerSearchApi::images/inst.png'); ?>" alt="Installer">  <?php }?>
							 </td>
                                
<td> <a target="_blank" href="<?php echo $store->getGoogleMap();?>"><?php echo $store->getAddress(); if($store->getAddress2()!=''){ echo $store->getAddress2();} ?> <?php if($store->getCity()!=''){echo ', '.$store->getCity().', ';} ?> <?php echo $store->getState() ?> <?php echo $country; ?> <?php echo $store->getZip() ?></td><td><?php echo $store->getPhone() ?></a></td>		
<td><?php  echo round($dis['miles']).'/'.round($dis['kilometers']);?></td>						 
                               </tr>
                            <?php endforeach ?>
                        </table>
                    <?php endif ?>
                </div>
            </div>
            <?php //echo $this->getPager() ?>
        </div>
       
    </div>
</div><?php } ?>