<?php
/**
 * Copyright (c) 2018 BORN Group, Inc. All rights reserved
 * @author Alexander Lukyanov
 *
 */
/** @var \Born\WebsiteStoreCreator\Block\WebsiteSwitcher $block */
?>
<?php if (count($block->getWebsites())>1): ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language-website">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger-website"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong>
                    <span><?php echo $block->escapeHtml($block->getCurrentWebsiteCountryName()) ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown" data-target="dropdown">
                <?php foreach ($block->getWebsites() as $website): ?>
                <?php if ($block->getCurrentShipToNumber()!=$block->getShipToNumberByWebsite($website)): ?>
                    <?php continue; ?>
                <?php endif;?>
                    <?php foreach ($website->getStores() as $_lang): ?>
                        <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                            <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                                <a href="#" data-post='<?= /* @noEscape */ $block->getTargetWebsitePostData($website, $_lang) ?>'>
                                    <?= $block->escapeHtml($block->getCountryNameByWebsite($website)) ?>
                                </a>
                            </li>
                        <?php else: ?>
                            <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option current-store" style="display: none">
                                <a href="#" data-post='<?= /* @noEscape */ $block->getTargetWebsitePostData($website, $_lang) ?>'>
                                    <?= $block->escapeHtml($block->getCountryNameByWebsite($website)) ?>
                                </a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>